version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file: .env
    command: pnpm run start:dev
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
